fresh-potatos/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from search import views as search_views
from django.contrib.auth import views as auth_views # import django's deafault backend authentication 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name="register"),
    path('profile/', user_views.profile, name="profile"),
    path('survey/', user_views.survey, name="survey"),
    path('survey_movies', user_views.survey_movies, name="survey_movies"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"), # 'LoginViews' is a class based view
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"), # built in views handles forms and logic for us. (not the templates)
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name="password_reset"), # 
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name="password_reset_done"), #the page that the user gets taken to after a password reset 
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name="password_reset_confirm"), #the link the user clicks on in the reset email they were sent
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name="password_reset_complete"), #
    path('', include('homepage.urls')),
    path('search/', search_views.search, name="search")
]

homepage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name="home"),
    path('about/', views.about, name="about"),
    path('FAQ/', views.faq, name="faq"), # add in FAQ page path
    path('farm/', views.farm, name="farm"),
    path('farmedit/', views.farmedit, name="farmedit"),
    path('more_info/<str:media_type>/<int:movie_id>/', views.more_info, ), # the <> brackets means the movie_num can be dynamic like a variable. Our int: means our input must be a string
    path('add_watch_later/<str:media_type>/<int:movie_id>/', views.add_watch_later),
    path('remove_watch_later/<str:media_type>/<int:movie_id>/<str:source>/', views.remove_watch_later),
    path('added_done/<str:media_type>/<int:movie_id>/', views.movie_added, name="added_movie_done")
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

class WatchLaterEntry(models.Model):
    title = models.CharField(max_length=300)
    media_type = models.CharField(max_length=100)
    movie_id = models.IntegerField()

    def __str__(self):
        return f'{self.title}'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField("Date of Birth", blank=True, null=True)
    genre = models.CharField(max_length=300, default="")
    stream = models.CharField(max_length=300, default="")
    watchlater = models.ManyToManyField(WatchLaterEntry)
    movies = models.CharField(max_length=1000, default="", blank=True)
    tv = models.CharField(max_length=1000, default="", blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms.widgets import DateInput
from .models import Profile
import os, sys
currentdir = os.path.dirname(os.path.realpath(__file__))
parentdir = os.path.dirname(currentdir)
sys.path.append(parentdir)
import api.api_get as api

class AddToMoviesForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['movies', 'tv']

class SearchForm(forms.Form):
    title = forms.CharField()
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class ProfileUpdateForm(forms.ModelForm):
    counter = 0
    context = {}
    for item in api.get_popular('movie')['results']:
        context[f'popular_movie{counter}'] = {
            "title": item['title'],
            "poster_path": item['poster_path'],
            "id":item['id'],
        }
        counter = counter + 1

    

    MOVIES = (
        (context['popular_movie0']['id'], context['popular_movie0']['poster_path']),
        (context['popular_movie1']['id'], context['popular_movie1']['poster_path']),
        (context['popular_movie2']['id'], context['popular_movie2']['poster_path']),
        (context['popular_movie3']['id'], context['popular_movie3']['poster_path']),
        (context['popular_movie4']['id'], context['popular_movie4']['poster_path']),
        (context['popular_movie5']['id'], context['popular_movie5']['poster_path']),
        (context['popular_movie6']['id'], context['popular_movie6']['poster_path']),
        (context['popular_movie7']['id'], context['popular_movie7']['poster_path']),
        (context['popular_movie8']['id'], context['popular_movie8']['poster_path']),
    )

    GENRES = (
        (28, 'Action'),
        (12, 'Adventure'),
        (16, 'Animation'),
        (35, 'Comedy'),
        (80, 'Crime'),
        (99, 'Documentary'),
        (18, 'Drama'),
        (10751, 'Family'),
        (14, 'Fantasy'),
        (36, 'History'),
        (27, 'Horror'),
        (10402, 'Music'),
        (9648, 'Mystery'),
        (10749, 'Romance'),
        (878, 'Science Fiction'),
        (10770, 'TV Movie'),
        (53, 'Thriller'),
        (10752, 'War'),
        (37, 'Western'),
    )

    SERVICES = (
        ('Netflix', 'Netflix'),
        ("Prime Video", 'Prime Video'),
        ('Crave TV', 'Crave TV'),
        ('Hulu', 'Hulu'),
        ('Disney+', 'Disney+'),
        ('HBO Max', 'HBO Max'),
        ('Other', 'Other')
    )

    dob = forms.DateField(label="Date of Birth", widget=forms.widgets.DateTimeInput(attrs={"type": "date"}))
    genre = forms.MultipleChoiceField(label="Genres", widget=forms.CheckboxSelectMultiple, choices=GENRES)
    stream = forms.MultipleChoiceField(label="What streaming services do you use?", widget=forms.CheckboxSelectMultiple, choices=SERVICES)
    # movies = forms.MultipleChoiceField(label="Select any movies that you like", widget=forms.CheckboxSelectMultiple, choices=MOVIES, required=False)
    class Meta:
        model = Profile
        fields = ['dob', 
                    'genre', 
                    'stream', 
                    # 'movies'
                    ]

users/views.py
from django.contrib import messages
from django.contrib.auth.forms import UsernameField
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Profile
from django.contrib.auth.models import User
from .forms import UserRegisterForm, ProfileUpdateForm, AddToMoviesForm
import os, sys
currentdir = os.path.dirname(os.path.realpath(__file__))
parentdir = os.path.dirname(currentdir)
sys.path.append(parentdir)
import api.api_get as api
from .forms import SearchForm
import logging

logger = logging.getLogger("mylogger")


def register(request):
    post = request.POST.copy()
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been create, please log in to complete your survey!')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

@login_required
def profile(request):
    profile = Profile.objects.get(user=request.user)
    print(profile.movies)
    movie_details = []
    for item in profile.movies.replace(' ','').replace('[','').replace(']','').replace("'",'').split(','):
        if item:
            temp = {
                'poster_path': api.get_details("movie", int(item))['poster_path'],
                'id': int(item)
            }
            movie_details.append(temp)
    tv_details = []
    for item in profile.tv.replace(' ','').replace('[','').replace(']','').replace("'",'').split(','):
        if item:
            temp = {
                'poster_path': api.get_details("tv", int(item))['poster_path'],
                'id': int(item)
            }
            tv_details.append(temp)
    genres = []
    for item in profile.genre.replace(' ','').replace('[','').replace(']','').replace("'",'').split(','):
        if item:
            for genre in api.get_genre("movie")['genres']:
                if int(item) == int(genre['id']):
                    genres.append(genre['name'])
    services = []
    for item in profile.stream.replace(' ','').replace('[','').replace(']','').replace("'",'').split(','):
        if item:
            services.append(item)

    context = {
        'movies':movie_details,
        'tv': tv_details,
        'genre':genres,
        'services':services,
    }
    return render(request, 'users/profile.html', context)


@login_required
def survey(request):
    if request.method == 'POST':
        logger.info(request.POST)
        p_form = ProfileUpdateForm(request.POST, instance=request.user.profile)
        if p_form.is_valid():
            p_form.save()
            messages.success(request, f'Updated')
            return redirect('survey_movies')
    else:
        p_form = ProfileUpdateForm(instance=request.user.profile)

    return render(request, 'users/survey.html', {'p_form': p_form})

@login_required
def survey_movies(request):

    # defining the search and putting it into context
    query = request.GET.get('search')
    if query is None:
        query = ""

    if query != "" :
        # fill results in categories
        context = {
            "query": query,
            "movie_results": api.search_movie_id(query)['results'],
            "tv_results": api.search_tv_id(query)['results']
        }
    else :
        context = {
            "query": query,
            "movie_results": {},
            "tv_results": {}
        }

    for item in context['movie_results']:
        item['poster_path'] = api.get_details("movie", item['id'])['poster_path']
    for item in context['tv_results']:
        item['poster_path'] = api.get_details("tv", item['id'])['poster_path']
    
    # grabs old movie list however it fetches its string so need to remove these characters [] ' "
    profile = request.user.profile
    tv = profile.tv
    tv = tv.replace('\'', '').replace('[', '').replace(']', '')
    movies = profile.movies
    movies = movies.replace('\'', '').replace('[', '').replace(']', '')

    logger.info(request.POST)

    if request.method == 'POST':
        post_value = request.POST.copy()
        selectedValues = str(post_value)

        # finds string movies and returns index, if not found then return -1
        try:
            indMov = selectedValues.index('movies\':')
        except ValueError:
            indMov = -1
        # finds string tv and returns index, if not found then return -1
        try:
            indTV = selectedValues.index('tv\':')
        except ValueError:
            indTV = -1

        # if the index of string isnt one, then remove the following characters from the string []'"
        if indMov != -1:
            strMovie = selectedValues[indMov + 7:indTV].replace('\'', '').replace('[', '').replace(']', '').replace(':', '').replace('>', '').replace('}', '')
            logger.info(strMovie)
        if indTV != -1:
            strTV = selectedValues[indTV + 3:].replace('\'', '').replace('[', '').replace(']', '').replace(':', '').replace('>', '').replace('}', '')
            logger.info(strTV)

        # checks if a movie has been selected

        if indMov != -1:
            strMovie = strMovie + ', ' + movies
        else:
            strMovie = movies

        strMovie = strMovie.replace(', ,', ',')
        if strMovie[-1] == ',':
            strMovie = strMovie[:-1]
        post_value['movies'] = strMovie
        
        #checks if a tv show has been selected
        if indTV != -1:
            strTV = strTV + ', ' + tv
            post_value['tv'] = strTV
        else:
            strTV = tv

        form = AddToMoviesForm(post_value, instance = request.user.profile)
        if form.is_valid():
            form.save()
            messages.success(request, f'Updated')
            return redirect('profile')

    return render(request, 'users/survey_movies.html', {'context': context})

users/templates/users/login.html
{% extends "homepage/base.html" %}
{% load crispy_forms_tags %} <!-- load in crispy form tags-->

{% block content %}
<div id="content-wrap">
    <div class="container movie-details">

        <div class= "row justify-content-md-center" style="width: 100%; height: 100%; overflow: hidden"> <!-- moves text to center-->
            
            <div class="col-md-auto" style="padding: 1rem">
                
                <legend style= "color: white">  Login to your Fresh Potatos Account: </legend>
                
            </div>
            
        </div>
        <div class= "row justify-content-md-center" style="width: 100%; height: 100%; overflow: hidden"> <!-- moves text to center-->
            <div class= "card">

                <div class= "card-body" style= "width: 30rem; padding: 1rem"> <!-- "card" class puts the fields in a "box"/card.  "width" increases card"s  with--> 

                    <div class= "container">
                            
                        <form method= "POST">
                <!-- LOGIN FIELDS-->
                            {% csrf_token %}  <!--  YOU MUST HAVE THIS OR IT WONT WORK! It stands for "cross site request forgery " token -- this protects form againts certian attacks-->
                    
                                
                            <fieldset class= "form-group">
                                <div class= "row justify-content-md-center">

                                        {{ form|crispy }} <!-- contains username and password field.  "|" spesifys we want to user a filter-->
                                    
                                </div> <!-- end legend justify-->
                                        
                            </fieldset>

                <!-- BUTTON -->
                            <div class= "row justify-content-md-center">

                                <div class= form-group>
                                    <button class= "btn btn-outline-info" type="submit"> Login</button>
                                </div>
                            </div> <!-- end buttin jusfity-->
                        </form>
                    </div> <!-- end of container-->
                </div> <!-- End of card-body-->
            </div> <!-- End of Card div -->
                    <div class= "row justify-content-md-center" style="width: 100%; height: 100%; overflow: hidden">
                <!-- REGISTER LINK-->
                        <small class= "text-muted">
                           <span style= "color: white;"> Don't have an Account Already?</span> <a class= "ml-2" href= "{% url 'register' %}"> Register Today!</a>
                        </small>
                    </div>
                    <div class= "row justify-content-md-center">
                <!-- FORGOT PASSWORD LINK-->
                        <small class= "text-muted">
                            <span style="color: white;">Forgot your Password?</span> <a class="ml-2" href= "{% url 'password_reset' %}"> Reset Password</a>
                        </small>
                    </div>
        </div>
    </div>
</div>
        

    
    
{% endblock %}

users/templates/users/logout.html
{% extends "homepage/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div id="content-wrap">
    <div class="container movie-details">
        <div class= 'row justify-content-md-center'>
            <div class= 'col-md-auto'>
                
                <h1 style= "color: white"> You Have Been Logged Out. </h1>
                <div class= "card">
                    <div class= "card-body">

                        <div class= "row justify-content-md-center mt-auto">
                            
                            <small> We hope your potatos were fresh! </small>
                            
                        </div>  
                        <div class= "row justify-content-md-center">
                            <small>Come back soon :)</small>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class= 'row justify-content-md-center'>
            <div class= 'col-md-auto mt-auto'>
                
                <small>
                    <a href= "{% url 'login' %}">Log Back In</a>
                </small>
                
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset.html
{% extends "homepage/base.html" %}
{% load crispy_forms_tags %} <!-- load in crispy form tags-->

{% block content %}


    <div class= "row justify-content-md-center"> <!-- moves text to center-->
        <div class= "card">
             

            <div class= "card-body" style= "width: 30rem; padding: 1rem"> <!-- "card" class puts the fields in a "box"/card.  "width" increases card"s  with--> 

                <div class= "container">
                        
                    <form method= "POST">
            <!-- LOGIN FIELDS-->
                        {% csrf_token %}  <!--  YOU MUST HAVE THIS OR IT WONT WORK! It stands for "cross site request forgery " token -- this protects form againts certian attacks-->
                
                            
                        <fieldset class= "form-group">
                            <div class= "row justify-content-md-center">
                                    

                                <center>
                                    <legend>  Reset Your Account Password </legend>
                                </center> 
                                    
                                {{form | crispy}} <!-- contains username and password field.  "|" spesifys we want to user a filter-->
                                    
                            </div> <!-- end legend justify-->
                                    
                        </fieldset>

            <!-- BUTTON -->
                        <div class= "row justify-content-md-center">

                            <div class= form-group>
                                <button class= "btn btn-outline-info" type="submit"> Request Password Reset</button>
                            </div>
                        </div> <!-- end buttin jusfity-->
                    </form>
                </div> <!-- end of container-->
                <div class= "row justify-content-md-center">

                    <!-- FORTOG EMIAL  LINK
                        
                        <small class= "text-muted">
                            <a class= "ml-2" href= "#"> Forgot Email?</a>
                        </small>
                    </div>
                -->
                
            </div> <!-- End of card-body-->
        </div> <!-- End of Card div -->
    </div>
        

    
    
    {% endblock %}

users/templates/users/password_reset_complete.html
{% extends "homepage/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
   

    <div class= "row justify-content-md-center">
        <div class= "alert alert-info">
            
            Your password has been reset!
            <div class= "row justify-content-md-center"> 
                <small class= "text-muted"> 
                    <a href="{% url 'login' %}"> Login to your account</a>
                </small>
            </div>
        </div>
    </div>



{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends "homepage/base.html" %}
{% load crispy_forms_tags %} <!-- load in crispy form tags-->

{% block content %}


    <div class= "row justify-content-md-center"> <!-- moves text to center-->
        <div class= "card">
             

            <div class= "card-body" style= "width: 30rem; padding: 1rem"> <!-- "card" class puts the fields in a "box"/card.  "width" increases card"s  with--> 

                <div class= "container">
                        
                    <form method= "POST">
            <!-- LOGIN FIELDS-->
                        {% csrf_token %}  <!--  YOU MUST HAVE THIS OR IT WONT WORK! It stands for "cross site request forgery " token -- this protects form againts certian attacks-->
                
                            
                        <fieldset class= "form-group">
                            <div class= "row justify-content-md-center">
                                    

                                <center>
                                    <legend>  Reset Your Account Password </legend>
                                </center> 
                                    
                                {{form | crispy}} <!-- contains username and password field.  "|" spesifys we want to user a filter-->
                                    
                            </div> <!-- end legend justify-->
                                    
                        </fieldset>

            <!-- BUTTON -->
                        <div class= "row justify-content-md-center">

                            <div class= form-group>
                                <button class= "btn btn-outline-info" type="submit"> Reset Password </button>
                            </div>
                        </div> <!-- end buttin jusfity-->
                    </form>
                </div> <!-- end of container-->
                <div class= "row justify-content-md-center">
            <!-- REGISTER LINK-->
                    <small class= "text-muted">
                        <a class= "ml-2" href= "#"> Forgot Email?</a>
                    </small>
                </div>
            </div> <!-- End of card-body-->
        </div> <!-- End of Card div -->
    </div>
        

    
    
    {% endblock %}

users/templates/users/password_reset_done.html
{% extends "homepage/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
   

    <div class= "row justify-content-md-center">
        <div class= "alert alert-info">
            <div class= "row justify-content-md-center">
                Please check your email for password reset instructions. 

            </div>
            <div class= "row justify-content-md-center  ">
                (Be sure to check your spam folder)
            </div>
            <br>
            <div class= "text-muted">

                <div class= "row justify-content-md-center">
                    <small> NOTE:  </small>
                </div>
                <div class= "row justify-content-md-center">
                    <small> **you will NOT get an email if you do not have an account** </small>
                    
                    
                </div>
            </div>

            <div class= "row justify-content-md-center"> 
                <small class= "text-muted"> 
                    <br>
                    <a href="{% url 'login' %}"> Login to your account</a>
                </small>
            </div>
        </div>
    </div>



{% endblock %}

users/templates/users/register.html
{% extends "homepage/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div id="content-wrap">
    <div class="container movie-details">
        <div class="row justify-content-md-center">
            <div class="col-md-auto" style="padding: 1rem">
                <legend style="color: white">Join Fresh Potatos Today for instant movie recommendations!</legend> 
            </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
                <form method="post">
                    {% csrf_token %}
                    <div class="card" style="width: 30rem; padding: 1rem">
                        <div class="card-body">
                            {{ form|crispy }}
                        </div>
                        <center>
                            <div class="form-group">
                                <button class="btn btn-outline-info" type="submit">Sign Up</button>
                            </div>     
                        </center>
                    </div>
                </form>    
            </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-md-auto" style="padding: 1rem">
                <small class="text-muted">
                    <span style="color: white">Already have an account? </span> <a class="ml-2" href="{% url 'login' %}">Log In</a>
                </small>   
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/survey.html
{% extends "homepage/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container" style="padding-bottom: 10rem;">
        <div class="row justify-content-md-center">
            <div class="col-md-auto" style="padding: 1rem">
                <legend style="color: white">Let us know a little bit about yourself!</legend> 
            </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card" style="width: 50rem; padding: 1rem">
                        <div class="card-body">
                            <div class="container">
                                <div class="row">
                                    <div class="col">
                                        {{ p_form.dob|as_crispy_field }}
                                        {{ p_form.genre|as_crispy_field }}
                                        {{ p_form.stream|as_crispy_field }}
                                    </div>

                                    <!-- Manually rendered movie choices -->
                                    <!-- <div class="container series">
                                        <label for="id_dob">Select the movies that you like</label>
                                        <div class="col-sm">
                                            {% for choice in p_form.movies.field.choices %}
                                                <label for="id_movies_{{ choice }}">
                                                    <img src="{{ choice.1 }}" name="{{ choice.0 }}"/>   
                                                </label> 
                                                <input type="checkbox" class="form-check-input" name="movies" id="id_movies_{{ choice }}" value="{{ choice.0 }}" {% if choice.0 in p_form.movies.value %} checked="checked"{% endif %} style="width:30px; height: 30px">
                                            {% endfor %}
                                        </div>    
                                    </div> -->
                                    
                                </div>
                            </div>
                        </div>
                        <center>
                            <div class="form-group">
                                <button class="btn btn-outline-info" type="submit">Continue</button>
                            </div>     
                        </center>
                    </div>
                </form>    
            </div>
        </div>
    </div>
{% endblock %}